{
package noam
}

Input <- node:Node EOF {
  return node, nil
}

Node <- _ "[" _ head:Identifier _ body:Body _ "]" _ {
  node := body.(*Node)
  node.Head = head.(string)
  return node, nil
}

Body <- leaf:Identifier {
   return &Node {
      Leaf: leaf.(string),
   }, nil
} / children:Node+ {
   return &Node {
         Children: makeChildren(children),
   }, nil
}

Identifier <- [a-zA-Z_] [a-zA-Z0-9_]* {
  return string(c.text), nil
}
  
_ "whitespace" <- [ \n\t\r]*

EOF <- !.
